### ISSUE TITLE
DNSCrypt, DNS over TLS, DNS over HTTPS

### ISSUE THREAD

**Issue by westurner** [julian-klode/dns66#264] opened 2018-04-09 01:29 UTC
https://en.wikipedia.org/wiki/DNSCrypt

https://en.wikipedia.org/wiki/DNS_over_TLS

https://en.wikipedia.org/wiki/DNS_over_HTTPS
- works with proxied networks that block non-DNS/non-HTTPS

- #260 mentions DNS over HTTPS
- https://arstechnica.com/information-technology/2018/04/how-to-keep-your-isps-nose-out-of-your-browser-history-with-encrypted-dns/
  - describes informal performance metrics
- https://www.deepdotweb.com/2017/11/08/google-enable-encrypted-dns-requests-android/
  - looks like DNS over HTTPS may eventually be an Android feature

What are some good recommendations for DNS over HTTPS in Java (that could be added to DNS66)?

**Comment by julian-klode** [comment] 2018-05-11 21:40
Duplicate of #11

**Closed by julian-klode** 2018-05-11 21:40 UTC
