### ISSUE TITLE
DNS66 not working on S9+

### ISSUE THREAD

**Issue by elpeter25** [julian-klode/dns66#258] opened 2018-03-22 07:52 UTC
Hi,

I've changed my phone from an S8+ to an S9+ and when I enable the DNS66 I can connect to nothing. It's like it wouldn't resolve any dns at all.

Has anyone else the same problem? Or you have it working on an S9+?

Thanks!!!

**Comment by elpeter25** [comment] 2018-03-22 07:58
I just sent the logcat. And also this is the error that I see I chrome:

DNS_PROBE_FINISHED_BAD_CONFIG

**Comment by jorgechavez40** [comment] 2018-04-09 15:39
Having the same issue on a S9+

**Comment by AndroidUser00110001** [comment] 2018-04-13 03:51
Similar issue here. When connection switches between WiFi and cell data DNS66 stops working. Websites just time out. Stopping and restarting DNS66 do sent fix issue. Just a reboot does until connection switches again.

**Comment by misku** [comment] 2018-04-18 14:54
I'd like to confirm @AndroidUser00110001 issue (Samsung Galaxy S9 plus). After switching between Wifi and Mobile data (both directions), no Internet connection is available. Stopping and starting DNS66 again helps.

**Comment by julian-klode** [comment] 2018-04-24 17:28
I'm afraid the S9+ might be too fast, and hence trigger issues in Android where Android fails to start a new VPN. I think there's an old bug report for that, but not sure.

**Comment by misku** [comment] 2018-04-24 17:33
DNS blocking from AdGuard does not work too. So it's not specific to DNS66.

**Comment by misku** [comment] 2018-04-24 18:24
Irony, just now got an OTA update:
* Kernel `4.9.59-13138380-QB17694735`
* Build number `R16NW.G965FXXS1ARD1`

DNS66 works fine, even after switching between mobile and Wifi networks back and forth.

**Comment by AndroidUser00110001** [comment] 2018-04-26 00:46
AdGaurd working perfectly fine with Samsung Internet Browser for me.

**Comment by tomchiverton** [comment] 2018-05-22 17:16
Let's close this now it works then?

**Comment by ckuethe** [comment] 2018-06-06 07:26
Also having this issue with 0.5.8 from fdroid on an S9+.

Will test with the personal repo and grab logs later today.

**Comment by beefjerky9** [comment] 2018-06-06 19:38
I am also having this issue with my AT&T Galaxy S9.

The kernel version is: 4.9.65-13087505
The build number is: R16NW.G960USQU1.ARBI

**Comment by arandomperson23** [comment] 2018-06-19 19:01
I'm also having the issue on an AT&T S9+, same kernel and build as the two above me. Seems that moving from wifi to data works but data to wifi requires a reboot.

**Comment by beefjerky9** [comment] 2018-06-22 23:40
Good news! I just got a software update for my AT&T S9 that fixes the issue.

The kernel version is: 4.9.65-13087505
The build number is: R16NW.G960USQS2ARF4

So, if you have AT&T, try checking for a software update.

**Comment by beefjerky9** [comment] 2018-06-23 15:43
I spoke too soon. It actually does work much better, and doesn't seem to fail on network change like it used to. However, after some random amount of time, it just stops working and needs a reboot. For example, I'll be on mobile data, and it works, but then just stops for what seems like no reason. What can I do to help you fix this?

**Comment by misku** [comment] 2018-06-25 09:21
@beefjerky9 Same for me. I thought it was fixed, because when manually switching from WiFi to cellular, it was still working. However, after some weeks of testing it would work for some time after the morning reboot and then during the day it would stop working at all. Reboot or turning off DNS66 helps.

**Comment by lyndon91** [comment] 2018-06-27 15:20
It's an Android Oreo 8.0 and maybe even 8.1 problem. This problem also occurs on Google's own pixels (8.0 at least), LG's G6 on 8.0 and maybe even custom roms on 8.1. Android Oreo and P have lot's of wifi and vpn issues as reported on a lot of forums. I can't believe this buggy wifi shit is happening again. This was the case in Android Kitkat, got fixed for a while in Android 5, 6 and 7 only now to get buggy again. 

[Neowin](https://www.neowin.net/news/google-addresses-android-81-oreo-vpn-issues-fix-to-be-released)
[VPN issue will get fixed in Android P](http://piunikaweb.com/2018/05/22/android-p-to-fix-wifivpn-issue-introduced-by-oreo-8-1/)

**Comment by beefjerky9** [comment] 2018-06-27 19:59
@lyndon91  This isn't the same issue that's being reported here. The issue with current S9/S9+ firmware is causing the issue on mobile data, and is not limited to WiFi. In addition, the DNS66 VPN never actually disconnects, it just stops passing data.

**Comment by lyndon91** [comment] 2018-06-27 20:23
@beefjerky9 "It’s worth pointing out that the problem started following the Android 8.1 Oreo update and it occurred only when a VPN connection was in use. However, it's worth noting that apps that rely on an internet connection to work ran without issue after the VPN service was turned off."

"For a quick refresher, the problem in question basically prevents apps from accessing the Internet through WiFi during a VPN connection." Just to add, it would prevent all internet to blocked.

This is exactly what is also happening with DNS66 and any other "VPN"-ish adblocker when you switch to data and back to wifi.  The system doesn't properly set the proper settings for the VPN to work so the connection gets blocked entirely. Did you even read the links?

**Comment by beefjerky9** [comment] 2018-06-27 20:32
@lyndon91 I did read the links, which state that the problem was introduced in the 8.1 update. Note that these phones are still running Android 8.0.0, so it definitely doesn't apply to us. Perhaps Samsung is avoiding 8.1 because of this and other issues. 

And to reiterate, with the most recent firmware update on the S9, I am losing connection while running solely on mobile data, which is not the same issue as described in your links. The most recent firmware seems to have fixed the original issue of losing connection on switching networks, but created a different one. 

What you quoted in your reply here also states it only started happening in Android 8.1, which does not apply us since we still run 8.0.0.

**Comment by lyndon91** [comment] 2018-06-27 21:05
1) The problem is the same: no connection when on VPN. Whether it was in 8.0 or 8.1 it's there for me on 8.0 and for people on 8.1. So the essence of the article is correct, the problem has the same root cause, the same files/code is involved, even tho the version number isn't the same as in this forum.
2) I've read somewhere on xda that manufacturers sometimes cherry pick stuff from a version after the version it's releasing. So Samsungs 8.0 may be a hybrid 8.0 x 8.1 causing it to have the same problems as people on 8.1.

**Comment by beefjerky9** [comment] 2018-06-27 21:07
@lyndon91 OK, you win.

@everyone else: I had a Pixel 2 for awhile with Android 8.1 and had zero issues with DNS66. It is definitely a Samsung issue.

**Comment by lyndon91** [comment] 2018-06-27 22:09
@beefjerky9 LG G6 has the same problem bro...

**Comment by brickmasterj** [comment] 2018-07-07 14:13
A possible solution could be to have a switch in DNS66 that sets it to only operate on mobile data, and use AdGuard DNS on all wifi networks. This would sort of work for the time being while Samsung gets their Android P updates ready.

**Comment by ckuethe** [comment] 2018-07-18 07:48
Build: `R16NW.G965USQS2ARF4`
Kernel: `4.9.56-13734144`

Has worked for 15 minutes and has survived flipping between wifi and mobile data a few times. Here's hoping it stays working.

**Comment by beefjerky9** [comment] 2018-08-26 09:01
Still the same issue with the latest AT&T Samsung firmware:
Build: R16NW.G960USQU3ARG7
Kernel: 4.9.65-13916502

I don't think Samsung is going to fix this. Any chance the wonderful DNS66 developer will be able to find a workaround?

**Comment by beefjerky9** [comment] 2019-02-09 08:09
Well, I thought I'd update this now that the 9.0 update is out. It runs fine in the background and doesn't cause me to lose all internet. However, it also doesn't block ads at all. No idea what Samsung screwed up this time. Anyone else with the same experience?

Build: PPR1.180610.011.G960USQU3CSAB
Kernel: 4.9.112-15119402

**Comment by ckuethe** [comment] 2019-02-10 01:11
I gave up and switched to [PersonalDNSFilter](https://github.com/IngoZenz/personaldnsfilter/) ([FDroid](https://f-droid.org/en/packages/dnsfilter.android/))

**Comment by beefjerky9** [comment] 2019-02-10 01:15
> I gave up and switched to PersonalDNSFilter (FDroid)

I wasn't aware of that one; I will have to give it a try. Are you running Pie, or still running Oreo? What filters are you using?

Thanks!

**Comment by lyndon91** [comment] 2019-02-10 01:15
Make sure you have async DNS resolving off in Chrome then it works perfectly on Android Pie.

That's [Chrome://flags/#enable-async-dns](Disable DNS)

**Comment by beefjerky9** [comment] 2019-02-10 01:35
> Make sure you have async DNS resolving off in Chrome then it works perfectly on Android Pie.
> That's [Chrome://flags/#enable-async-dns](Disable DNS)

That actually seems to work, at least for Chrome and the Google app. I sometimes use Samsung's internet browser, and it doesn't seem to block ads there, so I'm guessing they must use a similar thing with their DNS? Do you know of a similar setting for that browser?

**Comment by lyndon91** [comment] 2019-02-10 01:40
Maybe this can help

[XDA forums](https://forum.xda-developers.com/general/help/samsung-internet-advanced-settings-flags-t3594966)

**Comment by beefjerky9** [comment] 2019-02-10 01:50
> Maybe this can help
> XDA forums

I checked that out, but there's no setting in there for DNS. However, I came across this thread here:
https://www.reddit.com/r/GalaxyS9/comments/a94im7/blocking_ads_without_additional_software_in/

There's a post in there that shows Samsung Internet does indeed do something similar to what Chrome does by default with the DNS. However, the only way to disable it is to block a particular domain.

However, I wasn't aware of the personal DNS option that Android Pie offers, and I wonder how it compares to using DNS66. It would be nice to be able to block ads without additional software running. I just have to do some research and try to pick a reputable DNS to use.

Has anyone else here tried the personal DNS method in Pie?

**Comment by ckuethe** [comment] 2019-02-10 03:09
> > I gave up and switched to PersonalDNSFilter (FDroid)
> 
> I wasn't aware of that one; I will have to give it a try. Are you running Pie, or still running Oreo? What filters are you using?
> 
> Thanks!

Oreo 8.0.0 - last time I checked (4 hours ago) Pie was not available for my phone, and to be frank I'm scared of what'll break when I do upgrade.

For filters, I'm using the preset adaway+pgl+malware+ads/tracking sets, along with some [extra hosts](https://gist.github.com/ckuethe/15a532850744682fb0c2a668bee0b07f) of my own choosing

**Comment by lyndon91** [comment] 2019-02-10 03:10
> > Make sure you have async DNS resolving off in Chrome then it works perfectly on Android Pie.
> > That's [Chrome://flags/#enable-async-dns](Disable DNS)
> 
> That actually seems to work, at least for Chrome and the Google app. At least for the moment. We'll see if it quits working after awhile like it did in Oreo.
> 
> I sometimes use Samsung's internet browser, and it doesn't seem to block ads there, so I'm guessing they must use a similar thing with their DNS? Do you know of a similar setting for that browser?

They do block ads, but your filters aren't set up as tight as on say uBlock origin or Adblock plus on pc. DNS66 only has few filters out of the box installed. I just tested Samsung Internet and it DOES block ads as tested on [the Pi-Hole Website](https://pi-hole.net/pages-to-test-ad-blocking-performance/).

**Comment by beefjerky9** [comment] 2019-02-10 06:24
> Make sure you have async DNS resolving off in Chrome then it works perfectly on Android Pie.
> That's [Chrome://flags/#enable-async-dns](Disable DNS)
> 
> That actually seems to work, at least for Chrome and the Google app. At least for the moment. We'll see if it quits working after awhile like it did in Oreo.
> I sometimes use Samsung's internet browser, and it doesn't seem to block ads there, so I'm guessing they must use a similar thing with their DNS? Do you know of a similar setting for that browser?
> 
> They do block ads, but your filters aren't set up as tight as on say uBlock origin or Adblock plus on pc. DNS66 only has few filters out of the box installed. I just tested Samsung Internet and it DOES block ads as tested on the Pi-Hole Website.

I have all the host files selected in DNS66 (8), and it does block them on the Pi-Hole website in Chrome, but not Samsung Internet for me. I don't know what the difference is between yours and mine.

As referenced in the Reddit link I posted above, Samsung Internet does have it's own DNS server that it uses on port 53, with no way to disable it aside from blocking its port 53 access.

**Comment by julian-klode** [comment] 2019-02-10 09:04
Dns66 could also hijack other DNS servers, as long as they only do DNS. I should add full packet forwarding support so we can hijack anything.

FWIW, the default Steve black filter list in 0.6 is pretty decent, it includes most of the others and a whole bunch more. I certainly get better filtering than with 0.5.8. Only on F-Droid so far, binaries here will come today / tomorrow.

**Comment by julian-klode** [comment] 2019-09-07 10:32
Closing this issue, there does not seem anything actionable here.

**Closed by julian-klode** 2019-09-07 10:32 UTC
