### ISSUE TITLE
[Request] Traffic Logs Support

### ISSUE THREAD

**Issue by zero77** [julian-klode/dns66#100] opened 2017-04-01 15:19 UTC
Can you please add a log window that shows blocked and allowed traffic, and an option to allow specific block requests through.

Also, can you give the user the option to enable or disable this feature, to prevent unnecessary battery and resource usage.
Thanks

**Comment by julian-klode** [comment] 2017-04-01 17:45
Duplicate of #35 - will come at some point, but need to think about the details first

**Closed by julian-klode** 2017-04-01 17:45 UTC
