### ISSUE TITLE
Dan Pollack's host file Error 302:found

### ISSUE THREAD

**Issue by tomhusband** [julian-klode/dns66#301] opened 2018-08-07 20:20 UTC
I haven't been unable to update this host file for several days now. I set it to ignore but am I losing some protection? 

Thanks

**Comment by Neodymium5312** [comment] 2018-08-07 20:27
Did you try changing the url to https? I got it working myself by doing this

**Comment by Neodymium5312** [comment] 2018-08-07 20:28
Duplicate of issue #292 probably is already in https://github.com/julian-klode/dns66/pull/292

**Comment by tomhusband** [comment] 2018-08-07 20:31
Perfect. Changing it to https did it. Thanks Neodymium5312.

**Comment by Neodymium5312** [comment] 2018-08-07 20:33
Of course. Try making sure the issue isn't duplicate before posting in the future though

**Comment by tomhusband** [comment] 2018-08-07 20:40
Got it. Although if I search for "Error 302:found" nothing is found. I'll read up on proper use of Github.

Thanks again

**Comment by dctr** [comment] 2018-09-24 23:10
https://github.com/julian-klode/dns66/blob/458de23abe6ff0751c598bdd1399f4c832fb2604/app/src/main/java/org/jak_linux/dns66/db/RuleDatabaseItemUpdateRunnable.java#L176 only counts `200` as valid. It should maybe say `responseCode < 400`.

**Comment by julian-klode** [comment] 2018-09-25 07:00
> [dns66/app/src/main/java/org/jak_linux/dns66/db/RuleDatabaseItemUpdateRunnable.java](https://github.com/julian-klode/dns66/blob/458de23abe6ff0751c598bdd1399f4c832fb2604/app/src/main/java/org/jak_linux/dns66/db/RuleDatabaseItemUpdateRunnable.java#L176)
> 
> Line 176 in [458de23](/julian-klode/dns66/commit/458de23abe6ff0751c598bdd1399f4c832fb2604)
> 
>  if (connection.getResponseCode() != 200) { 
> only counts `200` as valid. It should maybe say `responseCode < 400`.

No. Unless you want an empty/wrong file (the body of the redirect, rather than the file).

**Comment by julian-klode** [comment] 2019-01-15 20:46
See #293

**Closed by julian-klode** 2019-01-15 20:46 UTC
