### ISSUE TITLE
How to spy on apps?

### ISSUE THREAD

**Issue by hklene** [julian-klode/dns66#174] opened 2017-08-10 06:41 UTC
Hello

I imagine dns66 building up a big map of which URL was accessed by which app. Then it would be possible to select one App and view all the URL's contacted by it.

Also in reverse this could be interesting: Select some URL and ask who tried to access it? Probably to be more useful, one would want to select a domain or only a partial search keyword and see all matching URLs within along with all apps that accessed at least one of those.

If the map grows to big, just discard older entries and offer the user a tradeoff, how long into the past URLs may be tracked vs. how much space this would require. The feature could also be off by default and only enable for certain suspicious apps.

As of now, your app is just a black box, that most of the time just works. This feature would hopefully empower the user to do more than just toggling DNS on and off, once some app starts malfunctioning. Ultimately I see this as a first step to modify and finetune the block rules to my personal liking. I might even allow ads in a certain app, to explicitly support its developer, while denying the very same add-URL for another app.

**Comment by sonho666** [comment] 2017-08-11 16:25
Some sort of DNS listener would be greatly appreciated.

For anyone interested in a workaround. I use the netguard on F-droid when some app misbehave and manually insert the url found on DNS66.

It would be awesome if I could do it all from DNS66 or, at least, be able to block all DNS requests from given app that do not need internet connection as in #170

**Comment by julian-klode** [comment] 2017-08-26 11:18
This is a duplicate of #35

**Closed by julian-klode** 2017-08-26 11:18 UTC

**Comment by hklene** [comment] 2017-08-28 12:28
Actually I hoped for this feature to grow bigger into a rule-editor to further customize the rules on an per App level. Way beyond "5% URLs blocked"-summary ... And popping up an endless unformatted logfile won't help either.
