### ISSUE TITLE
Auto Update Hosts

### ISSUE THREAD

**Issue by CritiKILL** [julian-klode/dns66#110] opened 2017-04-16 18:47 UTC
Please make this priority. DNS66 not auto updating is really a pain, and I would really like this implemented. Thanks you and this app is one of the best Android adblockers, I really appreciate your work.

**Comment by julian-klode** [comment] 2017-04-16 21:15
A pain is certainly an overstatement. You could not update for weeks and still have a decent ad blocking experience. That said, this is a duplicate of issue #2 and automatic updates landed 23 hours ago. The following requirements need to be satisfied for an update to run: The device is charging, on an unmetered network, and idle.

You can try this out for yourself in the beta posted in https://forum.xda-developers.com/showpost.php?p=71878450&postcount=458.

Error handling is not pretty yet. If pending downloads were cancelled, they might be retried (not 100% sure...), but it's not retrying on errors in general. Need to differentiate between temporary errors that are worth retrying (Timeout, Name lookup failure, Cancelled) and non-persistent ones (like a Not Found).

**Closed by julian-klode** 2017-04-16 21:15 UTC
