### ISSUE TITLE
The logcat improvement

### ISSUE THREAD

**Issue by klirick1** [julian-klode/dns66#307] opened 2018-09-04 17:13 UTC
I think you must improve the logcat to be better
This my recommendation to improve the logcat
https://git.frostnerd.com/PublicAndroidApps/DnsChanger/
In that app use query log to see what link are accessed from dns, its better visualization but not detail
Thank you :D

**Comment by mohag** [comment] 2019-01-04 13:18
It would be nice to have a log of recent requests with their allowed / blocked status in the app directly... (possibly filtered to only show blocked requests by default)

**Comment by julian-klode** [comment] 2019-01-10 07:33
I assume what you mean here is a duplicate of #35 (in-app viewing of dns requests and blocks/accept)?

**Comment by mohag** [comment] 2019-01-10 07:53
@julian-klode My part yes... (I'm not sure if @klirick1 actually wants it in logcat in a different format than currently as well...) (If they just want an easy way to see the DNS details, for which #35 might work, or if they have another use case...)

**Closed** 2019-09-07 10:23 UTC
