### ISSUE TITLE
[question] still no dns encryption?

### ISSUE THREAD

**Issue by kcris** [julian-klode/dns66#422] opened 2020-12-30 02:04 UTC
hi

this is about ad-blocking done by intercepting dns requests, 

so, since we're talking about dns (and privacy), 
this app would be a perfect solution 
*only if*
there were support for dns-over-https / dns-over-tls

(when talking to upstream dns servers, 
not to the local vpn service, obviously)

so, still no such support?
All I could find was this old thread, started 4 years ago: https://github.com/julian-klode/dns66/issues/11

Without such support in dns66, I can just use `Private DNS` setting available on Android 9+ 
paired with a dns provider that does ad-blocking,
some examples here - https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/public-resolvers.md

and I'll get both adblocking *and* use a custom DNS provider 
and we can get dns encryption too

dns66 offers some improved client-side-ad-blocking
but without dot/doh, I will lose the dns encryption.

thanks

**Comment by julian-klode** [comment] 2021-01-02 12:07
Duplicate of #11

**Closed** 2021-01-02 12:07 UTC
