### ISSUE TITLE
Problem on Galaxy S9+

### ISSUE THREAD

**Issue by TotoTataJa** [julian-klode/dns66#288] opened 2018-06-23 14:41 UTC
Hi,
I previously had a rooted Notes 4 with adaway app installed that died last week.
I bought a brand new Galaxy S9+ and don't want to root it at the moment (no interesting custom ROM) so I'm trying DNS66 but it doesn't work at all.
As soon as the VPN is up (Wifi or GPRS Data), I cannot get anything working. 
It doesn't resolve any host I'm trying to reach.
When VPN is up and I try to update hosts files (only Adaway for the moment), I get the following error :
Unexpected error :
java.net.UnknownHostException: Unable to resolve host "adaway.org": No address associated with hostname.

I have tried enabling and disabling Custon DNS servers without any success.
I've tried starting Logcat but it doesn't work with java.lang.RunTimeException: Failure from system.
I have French language and tried to switch to English but it doesn't change also.
I really don't know what to do but I really want to get ride of those fuc...g adds.
Can you help me please?
Thanks

**Comment by ckuethe** [comment] 2018-06-24 05:37
Duplicate of #258?

**Comment by TotoTataJa** [comment] 2018-06-24 06:45
It seems to be very similar but, for me, it has never worked. It's not a switching problem as it doesn't work at all in both wifi or data. But thanks four pointing me to this issue.

**Comment by julian-klode** [comment] 2019-01-10 07:36
Dupe of #258

**Closed by julian-klode** 2019-01-10 07:36 UTC
