### ISSUE TITLE
Android Pie

### ISSUE THREAD

**Issue by shadowx360** [julian-klode/dns66#302] opened 2018-08-08 00:24 UTC
DNS66 stopped working (all ads are shown in browser) as soon as I updated Pixel XL to Android Pie release. Reinstalled multiple times. Another similar app is still working so it's specific to DNS66. Reproduced issue on Pixel 2 XL.

**Comment by mchelen** [comment] 2018-08-08 04:05
Duplicate of #289

**Comment by julian-klode** [comment] 2018-08-08 05:36
Closing as duplicate

**Closed by julian-klode** 2018-08-08 05:36 UTC
