### ISSUE TITLE
Not working with Spotify

### ISSUE THREAD

**Issue by labors89** [julian-klode/dns66#55] opened 2016-12-16 16:31 UTC
This is a great AdBlock but I can't figure out how to make it work with Spotify. With every other app or browser it works great.

I do not use the custom DNS servers, only the domain filters.

As side note, netguard works fine with Spotify and I use Steven black hosts on both apps.

Does dns66 use a different method of blocking ads?

Thank you :)

**Comment by julian-klode** [comment] 2016-12-16 16:35
Can you please clarify what do you mean with "Not working with Spotify #55"? Does spotify stop working for you, do you have ads in spotify, etc?

And yes, they are slightly different I think. Netguard redirects all traffic, DNS66 only traffic to DNS servers (and drops non DNS traffic to those right now).

**Comment by labors89** [comment] 2016-12-16 16:46
Sorry I wasn't clear.
I mean that it does not block ads from Spotify. But it's still active and blocking ads from chrome and other apps..
Every few songs I still get Spotify ads.

**Comment by julian-klode** [comment] 2016-12-16 17:00
Ah OK. I can't really help there, as I'm paying for Spotify Premium.  You might want to check if those hosts are really blocked (try a ping app or dns lookup app or something).

0.0.0.0 gads.pubmatic.com
0.0.0.0 spclient.wg.spotify.com

I'll check what the parser says about the file and if it adds them to the final blacklist.

That said, I really like the people at Spotify, and their ads are not really what I'm personally interested in blocking (I mostly wrote the app to have these awful popup banners and stuff blocked ...).

**Comment by labors89** [comment] 2016-12-16 17:28
Sure, I wasn't demanding or anything.  
Just genuine curious as why it didn't block. Might be a bug on the parser and maybe not only these address could be leaking.

I manually put these address on the block list and all seems gold :).

Awesome work.

**Comment by julian-klode** [comment] 2016-12-19 16:22
Hmm I just checked the parser and it correctly read these hosts from the file.

**Comment by smichel17** [comment] 2017-02-04 20:31
This is not a bug in DNS66.

It happens because spotify changed where they serve ads from, and the new servers, for whatever reason, have not made it into hosts file lists that I've found. 

I put up a txt file on my own website that contains the block below. When I add the link to DNS66, it successfully block ads in spotify (not linking to it because I don't want people to start using it and be upset if I move it or something).

**Comment by smichel17** [comment] 2017-03-07 17:01
@labors89 Made a gist you can use: https://gist.githubusercontent.com/smichel17/2ad8c3f18df64eb1d5a4b01d70646058/raw/91412355ee401f5795d05fe6d9bf74da8200fecc/spotads.txt

@julian-klode I think this can be closed.

**Comment by SMed79** [comment] 2017-03-07 21:35
Just FYI, for desktop web browser in [Adblock Plus](https://adblockplus.org/), AdBlock, µBo or Adguard add this filter :

`/mp3-ad/*$domain=open.spotify.com`
or
`||cloudfront.net/mp3-ad/`

**Comment by MrOats** [comment] 2017-03-17 23:17
Just experienced this issue only because of issue #66, else works fine over Wi-Fi using DNS66.

**Comment by MrOats** [comment] 2017-03-18 02:20
Well after fixing adjusting my Mobile Data Network to use IPv4 only, it has been blocking ads from Spotify (and other places too) just fine.

Can confirm now that blocking Spotify ads is fully functional through DNS66.

**Comment by julian-klode** [comment] 2017-03-18 10:57
OK, that should be fixed with the IPv6 support in master, see #4 and #68. There will be a release in the next days, so you can verify it yourself :)

**Closed by julian-klode** 2017-03-18 10:57 UTC
Labels: bug, help wanted
