### ISSUE TITLE
Allow local-resolving of real ip with hosts file

### ISSUE THREAD

**Issue by ccaapton** [julian-klode/dns66#198] opened 2017-09-13 01:10 UTC
Hi. Would it be pausible to implement local custom ip address resolving aside from the current block/ignore/allow action? To be more specific, I want to include a hosts file like
```
8.8.8.8 abc.com
```
so when any clients on android query for "abc.com", dns66 will reply with the ip address from the custom hosts file instead of relaying upstream dns server.

**Comment by monkeymagic29** [comment] 2017-09-13 20:19
Yes, it's totally possible. I've been implementing my own local hosts file because I wanna block analytics from few apps I have in my unrooted phone:
1. Install termux
2. apt update && apt install vim/your fav text editor
3. vim hosts (then write your blocklist)
4. Once you're done, click the + on HOSTS subsection
5. Click the paper clip icon and direct it to the file in your termux' home, name it if necessary. There's a possibility that you need to give termux permission over Storage.

**Comment by julian-klode** [comment] 2017-09-13 20:35
Duplicate of #86, and no, it's not implemented yet, only blocking-

**Closed by julian-klode** 2017-09-13 20:35 UTC

**Comment by monkeymagic29** [comment] 2017-09-13 20:44
Forgot to add:
When a hostname is being "blocked", it's really just you telling dns66 to enforce the provided hosts files. For example, 127.0.0.1 www.leanplum.com just means you're telling resolver that your localhost is www.leanplum.com, resulting it being "blocked", although it's probably more accurate to be called "redirected". Conversely, if you point xxx.xxx.xxx.xxx, which is real IP of website.address, in your hosts file, it'll just bypass dns lookup and go straight to the site. I could be wrong and Android handles DNS differently though.

**Comment by julian-klode** [comment] 2017-09-13 20:49
No monkeymagic. DNS66 ignores any lines containing IP addresses other than 127.0.0.1, 0.0.0.0, and ::1. And it does not respond with those IP addresses either, it sends an empty response, indicating that the name could not be resolved.
