### ISSUE TITLE
Feature request: Show internet activity log of apps

### ISSUE THREAD

**Issue by helperman** [julian-klode/dns66#398] opened 2020-06-13 14:00 UTC
Since all internet traffic goes through DNS66, it would be reasonable to see what application connects to which domain. Additionally it would be great to see which domain was blocked and which was not.

Here is how it's done in another app "NoRoot Firewall".
Red background shows blocked connections and green color shows allowed connections along with domain names or ip-addresses.
It would ease troubleshooting when some app doesn't work due to blocked domain.

![00000131](https://user-images.githubusercontent.com/8351863/84570621-4e16b780-ad97-11ea-81dc-53d0dac23d5a.png)

**Comment by julian-klode** [comment] 2020-06-13 16:27
Duplicate of #35

**Closed by julian-klode** 2020-06-13 16:27 UTC
